config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'
  
  get 'view_order' => 'cart#view_order'

  get 'view_user_orders' => 'cart#view_user_orders'

  get 'checkout' => 'cart#checkout'

  devise_for :users
  root 'storefront#all_items'

  get 'categorical' =>'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

# generates 7 routes for 5 product views
  resources :products

  post 'order_complete' => 'cart#order_complete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.admin?
        can :manage, Product
    elsif user.guest?
        can :show, Product
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :product
	belongs_to :order, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :line_items
	belongs_to :user, optional: true
	# we created the order_items as a text type, make it a hash
	serialize :order_items, Hash
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders

  def admin?
  	role == "admin"
  end

  def guest?
  	role == "guest"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :categories, :brands
	
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :role])
  end

  def categories
  	@categories = Category.order(:name)
  end

# Pluck grabs everything in one column - there will be multiples
# Where is :brand assigned a value?
# Where is this function called?
  def brands
  	@brands = Product.pluck(:brand).sort.uniq
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	before_action :authenticate_user!, except: [:add_to_cart, :view_order]
  def order_complete
    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

      customer = Stripe::Customer.create(
        :email => current_user.email,
        :card => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer => customer.id,
        :amount => @amount,
        :description => 'Rails Stripe customer',
        :currency => 'usd'
      )

      rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to cart_path
  end 

  def add_to_cart
  	line_item = LineItem.create(product_id: params[:product_id], quantity: params[:quantity])
    line_item.update(line_item_total: (line_item.quantity * line_item.product.price))

  	redirect_back(fallback_location: root_path)
  end

  def view_order
  	@line_items = LineItem.all
  end

  def view_user_orders
  	@orders = Order.pluck(current_user.id)
  end

  def checkout
  	line_items = LineItem.all
	  @order = Order.create(user_id: current_user.id, subtotal: 0)

	  line_items.each do |line_item|
	    line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))
	    @order.order_items[line_item.product_id] = line_item.quantity 
	    @order.subtotal += line_item.line_item_total
	  end
	  @order.save

	  @order.update(sales_tax: (@order.subtotal * 0.08))
	  @order.update(grand_total: (@order.sales_tax + @order.subtotal))

	  line_items.destroy_all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    authorize! :create, @product
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
    authorize! :update, @product
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    authorize! :destroy, @product
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand, :rating, :category_id, :image)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
  	@products = Product.all
  end

  def items_by_category
  	@products= Product.where(category_id: params[:category_id])
  	@category = Category.find(params[:category_id])
  end

  def items_by_brand
  	@products = Product.where(brand: params[:brand])
  	@brand = params[:brand]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/cart/add_to_cart.html.erb
<p> <%= controller.controller_name%>:add_to_cart</p>
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h1>Thanks for Shopping With Us!</h1>
<p>Let's review your order:</p>


<% @order.order_items.each do |key, value| %>
  <ul>
    <li><%= Product.find(key).name %></li>
    <li>Qty: <%= value %></li>
  </ul>
<% end %>

<p>
  <strong>Subtotal: </strong><%= number_to_currency @order.subtotal %> 
</p>

<p>
  <strong>Sales Tax: </strong><%= number_to_currency @order.sales_tax %> 
</p>

<p>
  <strong>Order Total: </strong><%= number_to_currency @order.grand_total %> 
</p>

<div>
  <%= form_tag order_complete_path do %>
    <div>
      <%= hidden_field_tag :order_id, @order.id %>
    </div>

    <script src="http://checkout.stripe.com/checkout.js"
    class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Order #<%= @order.id %>"
    data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
  <% end %>
</div>

app/views/cart/old_checkout.html.erb
<p> <%= controller.controller_name%>:checkout </p>
<h2>Thanks for shopping with us!</h2>
<p>Let's review your order:</p>

<!-- order_items is a hash, k is the product name, v is the product quantity -->
<% @order.order_items.each do |k,v| %>
  <ul>
    <li><%= Product.find(k).name %>, <%= v %></li>
  </ul>
<% end %>

<p>
  <strong>Order Total:</strong> <%= number_to_currency @order.grand_total %>
</p>

app/views/cart/order_complete.html.erb
<h2>Thank you for your order!</h2>

<p>
  Order #<%= @order.id %> will be shipping to you, 
  <!-- may not work with .name , might need to use .email-->
  <%= @order.user.name %> as soon as possible!
</p>

app/views/cart/view_order.html.erb
<p> <%= controller.controller_name%>:view_order </p>
<h2>My Cart</h2>
<div>
  <% @line_items.each do |line_item| %>
    <li><%= line_item.product.name %></li>
    <li><%= number_to_currency line_item.product.price %></li>
    <li>Qty: <%= line_item.quantity %></li>
    <li>Subtotal: <%= number_to_currency line_item.line_item_total %></li>
  <% end %>
</div>

<div>
  <%= link_to "Proceed to Checkout?", checkout_path, class: "btn btn-success" %>
</div>

app/views/cart/view_user_orders.html.erb
<p> <%= controller.controller_name%>:view_user_orders </p>
<!-- Get all orders belonging to current user -->
<h2>My Orders</h2>
<div>
	<!-- Before we got here, @orders is populated with all orders having the current user's id -->
  	<% @orders.each do |order| %>
  	<div class="col-xs-4">
	    <div class="well">
	    	<!-- For each item on the order's item_list -->
		  	<!-- order_items is a hash, k is the product name, v is the product quantity -->
			<% order.order_items.each do |k,v| %>
			  <ul>
			    <li><%= Product.find(k).name %>, <%= v %></li>
			  </ul>
			<% end %>
		</div>
	</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<p> <%= controller.controller_name%>:application.html.erb Top</p>
<!DOCTYPE html>
<html>
  <head>
    <title>EStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Build the Navbar -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "All Items", root_path, class: "navbar-brand" %>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
           <!-- added Day2 Slide3 -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% @categories.each do |category| %>
                <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
                <% end %>
              </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @brands.each do |brand| %>
                <li><%= link_to brand, branding_path(brand: brand) %></li>
              <% end %>
                <li><%= link_to 'All', root_path %></li>
            </ul>
          </li> 
        </ul>
      </div>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "View My Orders", view_user_orders_path%>
          </li>
          <li><%= link_to "View Cart", view_order_path%>
          </li>
          <ul class="nav navbar-nav navbar-right">
             <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Hello, <%= current_user.email %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>

        </ul>
      </div>

  </nav>
  <p> <%= controller.controller_name%>:application.html.erb before yeild </p>
  <div class="container">
    <%= yield %>
  </div>
  </div>
</body>

</html>

app/views/products/_form.html.erb
<p> <%= controller.controller_name%>:_form</p>
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <strong>Upload Product Image: </strong>
    <%= form.file_field :image %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :product_quantity %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :product_brand %>
  </div>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :product_rating %>
  </div>

  <div class="form-group">
    <%= form.select :category_id, @categories.collect { |c| [c.name, c.id]}, {include_blank: "Please select a category:"} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<p> <%= controller.controller_name%>:edit</p>
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p> <%= controller.controller_name%>:index</p>
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class = 'table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Rating</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= product.rating %></td>
        <td><%= product.category.name %></td>
        <td><%= link_to 'Show', product %></td>
        <% if can? :update, Product %>
            <td><%= link_to 'Edit', edit_product_path(product) %></td>
            <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Product %>
  <%= link_to 'New Product', new_product_path %>
<%end%>

app/views/products/new.html.erb
<p> <%= controller.controller_name%>:new</p>
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p> <%= controller.controller_name%>:show</p>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/storefront/_product_loop.html.erb
<p> <%= controller.controller_name%>:_product_loop</p>
	 <div class="row">
	  <% @products.each do |product| %>
	  <div class="modal fade" id="exampleModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	        <% if product.image.url.nil? == false %>
          		<p><%= image_tag product.image.url, size: 150, class: "img-responsive" %></p>
       		<% end %>
        	<h3><%= link_to product.name, product %></h3>
        	<p><%= number_to_currency product.price %></p>
        	<p>made by <%= product.brand %></p>
	      </div>
	      <div class="modal-footer">
	      	<p>
            <%= form_tag add_to_cart_path do %>
              <%= hidden_field_tag :product_id, product.id %>
              <%= number_field_tag :quantity, 1, placeholder: "How many?" %>
              <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
            <% end %>
          </p>
	      </div>
	    </div>
	  </div>
	</div>

    <div class="col-xs-4">
      <div class="well">
        <% if product.image.url.nil? == false %>
          <p><%= image_tag product.image.url, size: 50, class: "img-responsive" %></p>
        <% end %>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
        	<!-- Adding in boostrap modal -->
          <a href="#" data-toggle="modal" data-target="#exampleModal_<%= product.id%>"> 
            <span class="glyphicon glyphicon-plus"></span> Quick Info
          </a>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/storefront/all_items.html.erb
<p> <%= controller.controller_name%>:all_items</p>
 <h1>All of our stuff for sale</h1>
 <!-- render the partial -->
<%= render "product_loop" %>

app/views/storefront/items_by_brand.html.erb
<p> <%= controller.controller_name%>:items_by_brand</p>
<h1>All or our <%= @brand %> products</h1>
<%= render "product_loop" %>

app/views/storefront/items_by_category.html.erb
<p> <%= controller.controller_name%>:items_by_category</p>
<h1>All of our <%= @category.name %></h1>
<%= render "product_loop" %>